// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD11UKJdUZalcciZ8hsIB89fWh_yJFFXzw',
    appId: '1:292281740205:web:e7242da689a9cf3b7b8f24',
    messagingSenderId: '292281740205',
    projectId: 'f-test-240e9',
    authDomain: 'f-test-240e9.firebaseapp.com',
    storageBucket: 'f-test-240e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBxyFXY9EK1QNvbnwVqwqpWGwsED8sNVw',
    appId: '1:292281740205:android:ec2db285db372b057b8f24',
    messagingSenderId: '292281740205',
    projectId: 'f-test-240e9',
    storageBucket: 'f-test-240e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGb1eQVGkGdmA28K-B_2PhXG4KoZJLVuk',
    appId: '1:292281740205:ios:50b10408781cd1797b8f24',
    messagingSenderId: '292281740205',
    projectId: 'f-test-240e9',
    storageBucket: 'f-test-240e9.appspot.com',
    iosClientId: '292281740205-qb1og0lavq85v0n19pk3jdtml438a0s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGb1eQVGkGdmA28K-B_2PhXG4KoZJLVuk',
    appId: '1:292281740205:ios:50b10408781cd1797b8f24',
    messagingSenderId: '292281740205',
    projectId: 'f-test-240e9',
    storageBucket: 'f-test-240e9.appspot.com',
    iosClientId: '292281740205-qb1og0lavq85v0n19pk3jdtml438a0s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fTest',
  );
}
